
name: Testar c칩digo Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o c칩digo do reposit칩rio
        uses: actions/checkout@v3

      - name: Configurar o ambiente com Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Executar o teste autom치tico
        run: python teste.py
